### PR TITLE
Skip @end@ meta package

### PR DESCRIPTION
**Pull request by nettnikl**

### CODE REVIEW

**Comment by jackwilsdon** [comment]
Do we know when these `@end@` packages are generated? I can't see a `@end@` key in my local backups and [can't find any mention of it in the Seedvault codebase](https://github.com/search?q=repo%3Aseedvault-app%2Fseedvault+%40end%40&type=code))

**Comment by nettnikl** [comment]
Interesting - i have no clue... Just saw it in a warning and in the metadata json

```
...
  "com.android.wallpaperbackup": {
        "time": 1684109833247,
        "backupType": "FULL",
        "system": true
    },
    "@end@": {
        "time": 1684118346539,
        "backupType": "KV",
        "system": true
    },
...
```

**Comment by nettnikl** [comment]
If anywhere, it should be here - but i also cannot find it.
https://github.com/seedvault-app/seedvault/blob/android13/app/src/main/java/com/stevesoltys/seedvault/metadata/MetadataWriter.kt

**Comment by jackwilsdon** [comment]
Hmm interesting. We support extracting KV backups as of e2875f747801b520a3ef7edb2979b8ffb7a0c9a6 - does it extract alright for you or are you missing the file for that entry?

**Comment by nettnikl** [comment]
`
error: failed to extract "@end@": failed to open "/home/user/seedvault_backup_parser-master/1677281112300/WkbEap08kh7AMAeENbupNYR-RO3nVgt3tRDBgwjEor1": open /home/user/seedvault_backup_parser-master/1677281112300/WkbEap08kh7AMAeENbupNYR-RO3nVgt3tRDBgwjEor1: no such file or directory
`

**Comment by nettnikl** [comment]
It doesn't extract, and seems to only be there to specify how long the backup took, timing-wise.

**Comment by jackwilsdon** [comment]
Fair enough, thank you for investigating!

**Pull request merged**
